# Use an official Ubuntu as a parent image
FROM ubuntu:22.04
LABEL authors="buitongnha"
# Update the package repository and install dependencies
RUN apt-get update  \
    && apt-get install -y wget \
    software-properties-common

# Install JDK 17
RUN add-apt-repository ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get install -y openjdk-17-jdk

# Set environment variables
ENV MAVEN_VERSION=3.9.8
ENV MAVEN_HOME=/usr/share/maven

# Install Maven
RUN wget -q https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && tar -xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /usr/share \
    && rm apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && ln -s /usr/share/apache-maven-${MAVEN_VERSION} /usr/share/maven \
    && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

# Set the working directory in the container
WORKDIR /backend
# Copy the Maven project files into the container
COPY . .

#RUN mvn wrapper:wrapper
#RUN mvn clean package -DskipTests
#RUN mvn clean install

EXPOSE 8080

# Run the JAR file
#CMD ["java", "-jar", "target/patching-management-0.0.1-SNAPSHOT.jar"]
ENTRYPOINT ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]
